before_script:
  - export http_proxy=$HTTP_PROXY
  - export https_proxy=$HTTP_PROXY

test:
    script:
        - rm -rf venv
        - python3 -m venv venv
        - source venv/bin/activate
        - pip install -r requirements.txt
        - make test
    tags:
        - pytest
    stage: test

sonar:
    script:
        - make sonar
    tags:
        - pylint
        - sonar
    stage: test
