before_script:
  - export http_proxy=$HTTP_PROXY
  - export https_proxy=$HTTP_PROXY
  #- echo -n $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

test:
    script:
        - make test
    tags:
        - pytest
    stage: test
sonar:
    script:
        - make sonar
    tags:
        - pylint
        - sonar
    stage: test
build:
    script:
        - make docker-build
    tags:
        - docker
    stage: build
deploy_cril:
    stage: deploy
    tags:
        - docker
    script:
        - cat $HOME/.docker/config.json
        - make docker-push
    needs: ["build"]
    environment:
        name: staging
    only:
        - web
