before_script:
  # docker login asks for the password to be passed through stdin for security
  # we use $CI_JOB_TOKEN here which is a special token provided by GitLab
  - echo -n $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

test:
    script:
        - make test
    tags:
        - pytest
    stage: test
sonar:
    script:
        - make sonar
    tags:
        - pylint
        - sonar
    stage: test
build:
    script:
        - make docker-build
    tags:
        - docker
    stage: build
deploy_cril:
    stage: deploy
    tags:
        - docker
    script:
        - docker push thibaultfalque/metrics:latest
    needs: ["build"]
    environment:
        name: staging
    only:
        - web