name: flat-dir-campaign
date: 23 septembre 2020

setup:
  os: Linux CentOS 7 (x86_64)
  cpu: Intel XEON X5550
  ram: 32GB
  timeout: 1200
  memout: 16384

source:
  path: example/flat-dir/input/data2/
  format: flat-dir
data:
  file-name-meta:
    pattern: ProblemFile-{any}_{word}_{any}
    experiment_ware: 2
    input_group: 1
  raw-data:
    - log-data:
        - cpu_time
        - mem
      regex: <global.*cpu="(\d+\.\d+)".*mem="(\d+M\d+)"
      group:
        - 1
        - 2
    - log-data: result
      pattern: Stop="{word}"
