name: flat-dir-campaign
date: 23 septembre 2020

setup:
  os: Linux CentOS 7 (x86_64)
  cpu: Intel XEON X5550
  ram: 32GB
  timeout: 1200
  memout: 16384

source:
  path: example/flat-dir/input/data2/
  format: single-file
data:
  file-name-meta:
    pattern: ProblemFile-{any}_{word}_{any}
    groups:
      experiment_ware: 2
      input: 1
  mapping:
    cpu_time: resolutions.resolution.solver.global.cpu
    mem: resolutions.resolution.solver.global.mem
    result: resolutions.resolution.solver.global.Stop
  data-files:
    - name: "*.xml"
      format: xml
