name: flat-dir-multiple-files-campaign
date: 23 septembre 2020

setup:
  os: Linux CentOS 7 (x86_64)
  cpu: Intel XEON X5550
  ram: 32GB
  timeout: 3600
  memout: 16384

source:
  path: example/flat-dir-multiple-files/input/data/
  format: multi-files
data:
  file-name-meta:
    regex: ([-a-z]+)_(.*).err
    groups:
      experiment_ware: 1
      input: 2
  raw-data:
    - log-data: cpu_time
      file: "*.err"
      pattern: "\\[runlim\\]\\s+real:\\s+(\\d+.\\d+)\\s+seconds"
    - log-data: derivation-step
      file: "*.out"
      pattern: "c number of derivation steps : {integer}"
      exact: true
    - log-data: conflicts
      file: "*.out"
      regex: "conflicts : {integer}"
      exact: false