name: multi-csv-with-custom-separator-and-no-header-campaign
date: 23 septembre 2020

setup:
  os: Linux CentOS 7 (x86_64)
  cpu: Intel XEON X5550
  ram: 32GB
  timeout: 1200
  memout: 16384

source:
  format: csv
  separator: ' '
  has-header: false
  path:
    - example/multi-csv-with-custom-separator-and-no-header/input/data/glu.txt
    - example/multi-csv-with-custom-separator-and-no-header/input/data/kissat.txt
data:
  file-name-meta:
    regex: (\w+)\.txt
    groups:
      experiment_ware: 1
  mapping:
    input: 0
    result: 1
    cpu_time: 2
